# Generated by Django 5.0.4 on 2024-07-02 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_amount', models.PositiveIntegerField(help_text='問題数')),
                ('genre', models.CharField(default='', help_text='????', max_length=1024)),
                ('giftPurchaseDate', models.DateTimeField(help_text='プレゼント買う日')),
                ('giftGivingDate', models.DateTimeField(help_text='プレゼント贈る日')),
                ('project_name', models.CharField(help_text='プロジェクト名', max_length=255)),
                ('budget', models.PositiveIntegerField(help_text='予算')),
                ('present_purpose', models.CharField(help_text='プレゼントの目的', max_length=255)),
                ('frequency', models.PositiveIntegerField(help_text='頻度')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField(help_text='年齢')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='性別', max_length=10)),
                ('relationship', models.CharField(help_text='関係', max_length=255)),
                ('receiver_name', models.CharField(help_text='名前', max_length=255)),
                ('hobbies', models.CharField(help_text='趣味', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='問題', max_length=1024)),
                ('answer', models.CharField(default='', editable=False, help_text='gpt答え', max_length=1024)),
                ('project', models.ForeignKey(help_text='対話', on_delete=django.db.models.deletion.PROTECT, related_name='message', to='app.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='receiver',
            field=models.ForeignKey(help_text='受け取り手', on_delete=django.db.models.deletion.PROTECT, related_name='project', to='app.receiver'),
        ),
        migrations.CreateModel(
            name='GiftHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gift', models.CharField(help_text='プレゼント', max_length=1024)),
                ('receiver', models.ForeignKey(help_text='受け取り手', on_delete=django.db.models.deletion.PROTECT, related_name='giftHistory', to='app.receiver')),
            ],
        ),
    ]
