# Generated by Django 5.0.4 on 2024-07-09 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='dueDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='締め切り'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='isCompleted',
            field=models.BooleanField(default=True, help_text='完了フラグ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='isCompleted',
            field=models.BooleanField(default=False, help_text='完了フラグ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='user_id',
            field=models.ForeignKey(default=1111, help_text='ユーザID', on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
