# Generated by Django 5.0.4 on 2024-07-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_createdat_message_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remark',
            field=models.CharField(default='it is a test', help_text='備考欄', max_length=255),
            preserve_default=False,
        ),
    ]
