# Generated by Django 5.0.4 on 2024-07-16 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(default=1, help_text='ユーザID', on_delete=django.db.models.deletion.PROTECT, related_name='project', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.CharField(default='', help_text='gpt答え', max_length=1024),
        ),
    ]
