# Generated by Django 5.0.4 on 2024-07-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_project_user_id_alter_message_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="present",
            field=models.CharField(
                blank=True, help_text="プレゼント", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="genre",
            field=models.CharField(default="", help_text="ジャンル", max_length=1024),
        ),
    ]
