# Generated by Django 5.0.4 on 2024-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_project_present_alter_project_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="prompt",
            field=models.CharField(
                blank=True, help_text="プロンプト", max_length=2048, null=True
            ),
        ),
    ]
